name: Build and deploy docs

on:
  pull_request:
  push:
    branches: [main]
    tags: ['*']

jobs:
  build-deploy-docs:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Build Docs
        run: make -C docs

      - name: Checkout docs site
        if: (!github.event.pull_request)
        uses: actions/checkout@v3
        with:
          repository: popsim-consortium/demes-spec-docs
          token: ${{ secrets.POPSIMBOT_DEMES_SPEC_DOCS_TOKEN }}
          path: demes-spec-docs

      - name: Copy our docs to the tag specific location
        if: (!github.event.pull_request)
        run: |
          cd demes-spec-docs
          export DEST=`echo ${GITHUB_REF} | sed -e "s/refs\/heads\///g" |  sed -e "s/refs\/tags\///g"`
          rm -rf $DEST
          cp -r ../docs/_build/html $DEST

      - name: Commit and push the docs
        if: (!github.event.pull_request)
        run: |
          cd demes-spec-docs
          git config user.name PopSim-bot
          git config user.email graham.gower+popsim-bot@gmail.com
          git add .
          git diff-index --quiet HEAD || git commit -m "Automated doc build for ${GITHUB_REF}"
          git push
