name: Run tests

on:
  pull_request:
  push:
    branches: [main]

jobs:
  tests:
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-24.04, windows-2022, macos-14]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: 3.12
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements_CI.txt
      - name: Tests for reference implementation
        run: |
          cd reference_implementation
          # Require 100% test coverage for reference implementation.
          python -m pytest \
            --cov=demes_parser \
            --cov-report=term-missing \
            --cov-fail-under=100 \
            tests.py
      - name: Tests for schema
        run: |
          python -m pytest tests.py
